// <auto-generated />
using System;
using DeliveryHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913212237_TipoTokenIFood")]
    partial class TipoTokenIFood
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryHub.Domain.Identity.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("DeveTrocarSenha")
                        .HasColumnType("boolean")
                        .HasColumnName("deve_trocar_senha");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("papel");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("DeliveryHub.Domain.Identity.UsuarioMerchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTimeOffset>("VinculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vinculado_em");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "MerchantId")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_merchant");

                    b.ToTable("usuario_merchants", (string)null);
                });

            modelBuilder.Entity("DeliveryHub.Domain.Merchants.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("IFoodMerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("ifood_merchant_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IFoodMerchantId")
                        .IsUnique()
                        .HasDatabaseName("ux_merchants_ifood_id");

                    b.ToTable("merchants", (string)null);
                });

            modelBuilder.Entity("DeliveryHub.Domain.Orders.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Indice")
                        .HasColumnType("integer")
                        .HasColumnName("indice");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco_total");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pedido_itens_pedido");

                    b.ToTable("pedido_itens", (string)null);
                });

            modelBuilder.Entity("DeliveryHub.Domain.Orders.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoNaOrigemEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_na_origem_em");

                    b.Property<bool>("EhTeste")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_teste");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_externo");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("NumeroExibicao")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("numero_exibicao");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxaEntrega")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("taxa_entrega");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno")
                        .IsUnique()
                        .HasDatabaseName("ux_pedidos_id_externo");

                    b.HasIndex("MerchantId", "RecebidoEm")
                        .HasDatabaseName("ix_pedidos_ativos_por_merchant")
                        .HasFilter("status IN ('Recebido','Confirmado','EmPreparo','Pronto','Despachado')");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("DeliveryHub.Infrastructure.Persistence.IntegrationInboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_event_id");

                    b.Property<Guid>("ExternalMerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_merchant_id");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_inbox_pendentes")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("Source", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_event");

                    b.ToTable("integration_inbox", (string)null);
                });

            modelBuilder.Entity("DeliveryHub.Domain.Merchants.Merchant", b =>
                {
                    b.OwnsOne("DeliveryHub.Domain.Merchants.ConexaoIFood", "ConexaoIFood", b1 =>
                        {
                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccessToken")
                                .HasColumnType("text")
                                .HasColumnName("ifood_access_token");

                            b1.Property<string>("AuthorizationCodeVerifier")
                                .HasColumnType("text")
                                .HasColumnName("ifood_authorization_code_verifier");

                            b1.Property<DateTimeOffset?>("CodigoExpiraEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ifood_codigo_expira_em");

                            b1.Property<DateTimeOffset?>("ConectadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ifood_conectado_em");

                            b1.Property<string>("RefreshToken")
                                .HasColumnType("text")
                                .HasColumnName("ifood_refresh_token");

                            b1.Property<string>("TipoToken")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ifood_tipo_token");

                            b1.Property<DateTimeOffset?>("TokenExpiraEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ifood_token_expira_em");

                            b1.Property<string>("UserCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ifood_user_code");

                            b1.HasKey("MerchantId");

                            b1.ToTable("merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantId");
                        });

                    b.Navigation("ConexaoIFood");
                });

            modelBuilder.Entity("DeliveryHub.Domain.Orders.ItemPedido", b =>
                {
                    b.HasOne("DeliveryHub.Domain.Orders.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliveryHub.Domain.Orders.Pedido", b =>
                {
                    b.OwnsOne("DeliveryHub.Domain.Orders.Cliente", "Cliente", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Localizador")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("cliente_localizador");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("cliente_nome");

                            b1.Property<string>("Telefone")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("cliente_telefone");

                            b1.HasKey("PedidoId");

                            b1.ToTable("pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.OwnsOne("DeliveryHub.Domain.SharedKernel.Endereco", "EnderecoEntrega", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("entrega_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("entrega_cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("entrega_cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("entrega_complemento");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("entrega_estado");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("entrega_latitude");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("entrega_logradouro");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("entrega_longitude");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("entrega_numero");

                            b1.Property<string>("Referencia")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("entrega_referencia");

                            b1.HasKey("PedidoId");

                            b1.ToTable("pedidos");

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.Navigation("Cliente")
                        .IsRequired();

                    b.Navigation("EnderecoEntrega");
                });

            modelBuilder.Entity("DeliveryHub.Domain.Orders.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
