// <auto-generated />
using System;
using DeliveryHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryHub.Domain.Merchants.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IFoodMerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("ifood_merchant_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IFoodMerchantId")
                        .IsUnique()
                        .HasDatabaseName("ux_merchants_ifood_id");

                    b.ToTable("merchants", (string)null);
                });

            modelBuilder.Entity("DeliveryHub.Domain.Orders.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("EhTeste")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_teste");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_externo");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno")
                        .IsUnique()
                        .HasDatabaseName("ux_pedidos_id_externo");

                    b.HasIndex("MerchantId", "RecebidoEm")
                        .HasDatabaseName("ix_pedidos_ativos_por_merchant")
                        .HasFilter("status IN ('Recebido','Confirmado','EmPreparo','Pronto','Despachado')");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("DeliveryHub.Infrastructure.Persistence.IntegrationInboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_event_id");

                    b.Property<Guid>("ExternalMerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_merchant_id");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_inbox_pendentes")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("Source", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_event");

                    b.ToTable("integration_inbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
